[package]
name = "murmur-relay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
aes-gcm = "0.10.1"
rand = "0.8"
base64 = "0.21.0"

